/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ValidateInitiative': EventHandler<never, { topic: 'initiative.validated'; data: never }>
    'UpdateMetrics': EventHandler<never, never>
    'UpdateEpic': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'epic.updated'; data: never }>
    'TestEndpoint': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetStrategyData': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'RecalculateGoalProgress': EventHandler<never, never>
    'NotifyGoalCreated': EventHandler<never, never>
    'InitializeState': EventHandler<never, never>
    'CreateInitiative': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'initiative.created'; data: never }>
    'CreateGoal': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'goal.created'; data: never }>
  }
}